# Generated by Django 2.2.5 on 2019-09-29 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
            ],
            options={
                'db_table': 'kelas',
            },
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjidev.Kelas')),
            ],
            options={
                'db_table': 'abstract',
            },
        ),
    ]
